---
- name: add autostart shortcut
  community.windows.win_shortcut:
    description: "{{ app_name }}"
    dest: "{{ autostart_user_dir }}\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\{{ app_name }}.lnk"
    src: "{{ executable_path }}"
    arguments: "{{ executable_arguments }}"
    directory: "{{ working_directory }}"
  notify:
    - reboot

- name: create shortcut to Startup directory for {{ autostart_user }}
  community.windows.win_shortcut:
    description: startup
    src: "%PROGRAMDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup"
    dest: "{{ autostart_user_dir }}\\Desktop\\Startup.lnk"
